services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '${HTTP_PORT}:80'
      - '${ADMIN_PORT}:81'
      - '${HTTPS_PORT}:443'
    volumes:
      - ${NGINX_DATA_PATH}:/data
      - ${NGINX_LETSENCRYPT_PATH}:/etc/letsencrypt
    networks:
      - default

networks:
  default:
    name: nginx_proxymanager_default
    ipam:
      config:
        - subnet: 172.18.0.0/16