version: '3.8'

services:
  database:
    image: docker.io/pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /srv/khoj/db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

  sandbox:
    image: ghcr.io/khoj-ai/terrarium:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 2
    networks:
      - default

  search:
    image: docker.io/searxng/searxng:latest
    restart: always
    volumes:
      - /srv/khoj/search:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    networks:
      - default

  computer:
    container_name: khoj-computer
    image: ghcr.io/khoj-ai/khoj-computer:latest
    restart: always
    ports:
      - "127.0.0.1:5900:5900"
    volumes:
      - /srv/khoj/computer:/home/operator
    networks:
      - default

  server:
    image: ghcr.io/khoj-ai/khoj:latest
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "127.0.0.1:42110:42110"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    volumes:
      - /srv/khoj/config:/root/.khoj/
      - /srv/khoj/models:/root/.cache/torch/sentence_transformers
      - /srv/khoj/models:/root/.cache/huggingface
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - KHOJ_DJANGO_SECRET_KEY=${KHOJ_DJANGO_SECRET_KEY}
      - KHOJ_DEBUG=${KHOJ_DEBUG:-False}
      - KHOJ_ADMIN_EMAIL=${KHOJ_ADMIN_EMAIL}
      - KHOJ_ADMIN_PASSWORD=${KHOJ_ADMIN_PASSWORD}
      - KHOJ_TERRARIUM_URL=http://sandbox:8080
      - KHOJ_SEARXNG_URL=http://search:8080
      - KHOJ_DOMAIN=${KHOJ_DOMAIN}
      - KHOJ_ALLOWED_DOMAIN=${KHOJ_ALLOWED_DOMAIN:-server}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: --host="0.0.0.0" --port=42110 -vv --non-interactive
    networks:
      - default
      - nginx_proxymanager_default

networks:
  nginx_proxymanager_default:
    external: true
