version: '3.8'

services:
  anythingllm:
    image: mintplexlabs/anythingllm
    # build:
    #   context: .
    #   dockerfile: Dockerfile.debug
    container_name: anythingllm
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - SERVER_PORT=3001
      - UID=1001
      - GID=1001
    ports:
      - "3001:3001"
    volumes:
      - /srv/anythingllm/storage:/app/server/storage
      - ./.env:/app/server/.env
    networks:
      - default
