services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ${OLLAMA_DATA_PATH}:/root/.ollama
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ${OPENWEBUI_DATA_PATH}:/app/backend/data
    ports:
      - "${OPENWEBUI_PORT}:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    restart: always
    depends_on:
      - ollama